### ISSUE TITLE
TypeError from check_return()

### ISSUE THREAD

**Issue by dahlia** [spoqa/tsukkomi#12]
``` pytb
Traceback (most recent call last):
  ...
  File "/.../python3.5/site-packages/tsukkomi/typed.py", line 204, in decorator
    check_return(call_.__name__, result, hints)
  File "/.../python3.5/site-packages/tsukkomi/typed.py", line 61, in check_return
    _, correct = check_type(r, hints['return'])
  File "/.../python3.5/site-packages/tsukkomi/typed.py", line 36, in check_type
    elif issubclass(hint, typing.Callable):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/typing.py", line 831, in __subclasscheck__
    return super().__subclasscheck__(cls)
TypeError: issubclass() arg 1 must be a class
```

**Comment by kanghyojun** [comment]
Is this error occured on 0.0.5? i think it fixed in 72eb2c3f13813898ae007d659a64c4fb6cf24a79

**Comment by dahlia** [comment]
Seems already fixed in 0.0.5 as you said. Sorry. I will close this.

**Comment by ipdae** [comment]
same problem in 0.0.6
